const sampleListings = [
  {
    ownerName: "Priya Sharma",
    dob: new Date("1992-08-15"),
    contact: "9876543210",
    category: ["Trending", "Iconic cities"],
    placeType: "Entire place",
    manualAddress: "123 MG Road, Bangalore",
    geometry: { type: "Point", coordinates: [77.5946, 12.9716] },
    location: "Bengaluru, Karnataka, India",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    image: { url: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop", filename: "listing_1" },
    title: "Modern City Center Apartment",
    description: "Stunning 2BHK apartment in the vibrant heart of the city. Close to shops, restaurants, and public transport.",
    price: 4500,
    residentialAddress: "A-101, Prestige Towers, Richmond Road, Bengaluru, Karnataka 560025, India",
    reviews: [],
  },
  {
    ownerName: "Raj Patel",
    dob: new Date("1988-03-22"),
    contact: "8765432109",
    category: ["Beaches", "Amazing pools"],
    placeType: "Entire place",
    manualAddress: "Near Baga Beach, Goa",
    geometry: { type: "Point", coordinates: [73.7533, 15.5577] },
    location: "Baga, Goa, India",
    guests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 3,
    image: { url: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop", filename: "listing_2" },
    title: "Luxury Beachfront Villa with Pool",
    description: "Escape to this beautiful villa steps from Baga Beach. Features a private pool and breathtaking ocean views.",
    price: 12000,
    residentialAddress: "Villa 7, Ocean View Estates, Calangute-Baga Road, Baga, Goa 403516, India",
    reviews: [],
  },
  {
    ownerName: "Anjali Mehta",
    dob: new Date("1995-11-01"),
    contact: "7654321098",
    category: ["Mountains", "Cabins"],
    placeType: "Private room",
    manualAddress: "Old Manali, Himachal Pradesh",
    geometry: { type: "Point", coordinates: [77.1887, 32.2432] },
    location: "Manali, Himachal Pradesh, India",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    image: { url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop", filename: "listing_3" },
    title: "Cozy Mountain Cabin Room",
    description: "A warm, inviting private room in a rustic wooden cabin with stunning Himalayan views.",
    price: 2500,
    residentialAddress: "House no. 54, Manu Temple Road, Old Manali, Himachal Pradesh 175131, India",
    reviews: [],
  },
  {
    ownerName: "Vikram Singh",
    dob: new Date("1985-06-30"),
    contact: "6543210987",
    category: ["Castles", "Iconic cities"],
    placeType: "Entire place",
    manualAddress: "Near Hawa Mahal, Jaipur",
    geometry: { type: "Point", coordinates: [75.8267, 26.9239] },
    location: "Jaipur, Rajasthan, India",
    guests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 4,
    image: { url: "https://images.unsplash.com/photo-1617592935934-f8155d31d348?auto=format&fit=crop", filename: "listing_4" },
    title: "Historic Haveli in the Pink City",
    description: "Experience royal living in this restored heritage haveli with intricate Rajasthani architecture.",
    price: 18000,
    residentialAddress: "12, Johari Bazar, Pink City, Jaipur, Rajasthan 302003, India",
    reviews: [],
  },
  {
    ownerName: "Sana Khan",
    dob: new Date("1990-01-25"),
    contact: "9988776655",
    category: ["Farms", "Countryside"],
    placeType: "Entire place",
    manualAddress: "Lonavala, Maharashtra",
    geometry: { type: "Point", coordinates: [73.406, 18.751] },
    location: "Lonavala, Maharashtra, India",
    guests: 10,
    bedrooms: 4,
    beds: 6,
    bathrooms: 4,
    image: { url: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop", filename: "listing_5" },
    title: "Sprawling Farmhouse with Garden",
    description: "A peaceful retreat from the city. This farmhouse is set amidst lush greenery, offering a serene and private stay.",
    price: 15000,
    residentialAddress: "Plot 34, Tungarli Village, Lonavala, Maharashtra 410401, India",
    reviews: [],
  },
  {
    ownerName: "Arjun Reddy",
    dob: new Date("1993-07-19"),
    contact: "8877665544",
    category: ["Iconic cities", "Rooms"],
    placeType: "Shared room",
    manualAddress: "Colaba, Mumbai",
    geometry: { type: "Point", coordinates: [72.8347, 18.922] },
    location: "Mumbai, Maharashtra, India",
    guests: 1,
    bedrooms: 1,
    beds: 1,
    bathrooms: 2,
    image: { url: "https://images.unsplash.com/photo-1521783599419-4137264b9b4a?auto=format&fit=crop", filename: "listing_6" },
    title: "Budget-Friendly Hostel Bed",
    description: "A single bed in a clean, modern, and friendly hostel. Perfect for backpackers and solo travelers exploring Mumbai.",
    price: 800,
    residentialAddress: "4th Floor, Backpacker's Inn, Apollo Bandar, Colaba, Mumbai, Maharashtra 400001, India",
    reviews: [],
  },
  {
    ownerName: "Meera Das",
    dob: new Date("1980-12-05"),
    contact: "7766554433",
    category: ["Arctic", "Mountains"],
    placeType: "Entire place",
    manualAddress: "Leh, Ladakh",
    geometry: { type: "Point", coordinates: [77.5771, 34.1526] },
    location: "Leh, Ladakh, India",
    guests: 4,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    image: { url: "https://images.unsplash.com/photo-1616584239832-86835251357c?auto=format&fit=crop", filename: "listing_7" },
    title: "High-Altitude Ladakhi Homestay",
    description: "Experience authentic Ladakhi hospitality with panoramic views of the Stok Kangri range.",
    price: 5000,
    residentialAddress: "Changspa Road, Near Shanti Stupa, Leh, Ladakh 194101, India",
    reviews: [],
  },
  {
    ownerName: "Rohan Kapoor",
    dob: new Date("1998-05-10"),
    contact: "6655443322",
    category: ["Amazing pools", "Trending"],
    placeType: "Entire place",
    manualAddress: "Udaipur, Rajasthan",
    geometry: { type: "Point", coordinates: [73.7125, 24.5854] },
    location: "Udaipur, Rajasthan, India",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    image: { url: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop", filename: "listing_8" },
    title: "Romantic Lakeside Suite with Pool",
    description: "A luxurious suite offering a private plunge pool and stunning views of Lake Pichola.",
    price: 9500,
    residentialAddress: "Suite 202, The Lake Palace Hotel, Udaipur, Rajasthan 313001, India",
    reviews: [],
  },
  {
    ownerName: "Isha Nair",
    dob: new Date("1991-09-03"),
    contact: "9123456780",
    category: ["Farms", "Countryside"],
    placeType: "Entire place",
    manualAddress: "Munnar, Kerala",
    geometry: { type: "Point", coordinates: [77.0595, 10.0889] },
    location: "Munnar, Kerala, India",
    guests: 5,
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    image: { url: "https://images.unsplash.com/photo-1603513409056-a798b3c65f04?auto=format&fit=crop", filename: "listing_9" },
    title: "Cottage in a Tea Plantation",
    description: "Live amidst the rolling hills of Munnar in this charming cottage surrounded by a tea garden.",
    price: 6000,
    residentialAddress: "Tea Garden Cottage, Pothamedu, Munnar, Kerala 685612, India",
    reviews: [],
  },
  {
    ownerName: "Aditya Verma",
    dob: new Date("1989-04-12"),
    contact: "9234567891",
    category: ["Iconic cities"],
    placeType: "Private room",
    manualAddress: "Hauz Khas Village, Delhi",
    geometry: { type: "Point", coordinates: [77.2167, 28.6738] },
    location: "New Delhi, Delhi, India",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    image: { url: "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop", filename: "listing_10" },
    title: "Artistic Room in Hauz Khas",
    description: "A stylish private room in a designer apartment overlooking the Hauz Khas lake and fort.",
    price: 3500,
    residentialAddress: "24, Hauz Khas Village, New Delhi, Delhi 110016, India",
    reviews: [],
  },
  {
    ownerName: "Neha Gupta",
    dob: new Date("1996-02-28"),
    contact: "9345678902",
    category: ["Trending", "Rooms"],
    placeType: "Private room",
    manualAddress: "Koramangala, Bangalore",
    geometry: { type: "Point", coordinates: [77.6245, 12.9345] },
    location: "Bengaluru, Karnataka, India",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    image: { url: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop", filename: "listing_11" },
    title: "Chic Room in Startup Hub",
    description: "Comfortable private room in a modern apartment in the heart of Koramangala.",
    price: 2800,
    residentialAddress: "Flat 5B, Zenith Apartments, 5th Block, Koramangala, Bengaluru, Karnataka 560095, India",
    reviews: [],
  },
  {
    ownerName: "Amit Desai",
    dob: new Date("1982-10-10"),
    contact: "9456789013",
    category: ["Beaches"],
    placeType: "Entire place",
    manualAddress: "Pondicherry, White Town",
    geometry: { type: "Point", coordinates: [79.8317, 11.9338] },
    location: "Puducherry, India",
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    image: { url: "https://images.unsplash.com/photo-1593053874261-24c15a3a2993?auto=format&fit=crop", filename: "listing_12" },
    title: "French Colonial Studio",
    description: "Charming studio apartment in the French Quarter (White Town), a short walk from the promenade.",
    price: 4000,
    residentialAddress: "No. 15, Rue Romain Rolland, White Town, Puducherry 605001, India",
    reviews: [],
  },
  {
    ownerName: "Sunita Roy",
    dob: new Date("1979-06-18"),
    contact: "9567890124",
    category: ["Iconic cities"],
    placeType: "Entire place",
    manualAddress: "Park Street, Kolkata",
    geometry: { type: "Point", coordinates: [88.3577, 22.5514] },
    location: "Kolkata, West Bengal, India",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    image: { url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop", filename: "listing_13" },
    title: "Vintage Apartment in City of Joy",
    description: "A beautifully maintained 2BHK with classic furniture, located on the iconic Park Street.",
    price: 5500,
    residentialAddress: "Flat 8C, Queens Mansion, Park Street, Kolkata, West Bengal 700016, India",
    reviews: [],
  },
  {
    ownerName: "Karan Malhotra",
    dob: new Date("1994-03-05"),
    contact: "9678901235",
    category: ["Mountains", "Cabins"],
    placeType: "Entire place",
    manualAddress: "Landour, Mussoorie",
    geometry: { type: "Point", coordinates: [78.0964, 30.4576] },
    location: "Mussoorie, Uttarakhand, India",
    guests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    image: { url: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop", filename: "listing_14" },
    title: "Quaint English Cottage",
    description: "A charming colonial-era cottage in the quiet cantonment of Landour, with a fireplace and valley views.",
    price: 7500,
    residentialAddress: "Ivy Cottage, Sisters Bazaar, Landour, Mussoorie, Uttarakhand 248179, India",
    reviews: [],
  },
  {
    ownerName: "Deepika Iyer",
    dob: new Date("1990-11-11"),
    contact: "9789012346",
    category: ["Amazing pools", "Countryside"],
    placeType: "Entire place",
    manualAddress: "Alibaug, Maharashtra",
    geometry: { type: "Point", coordinates: [72.8777, 18.6413] },
    location: "Alibaug, Maharashtra, India",
    guests: 8,
    bedrooms: 3,
    beds: 5,
    bathrooms: 3,
    image: { url: "https://images.unsplash.com/photo-1613977257363-31161384354c?auto=format&fit=crop", filename: "listing_15" },
    title: "Modern Villa with Infinity Pool",
    description: "A luxurious villa near Alibaug, perfect for a weekend escape with family and friends.",
    price: 20000,
    residentialAddress: "Villa 22, Hamptons, Awas, Alibaug, Maharashtra 402201, India",
    reviews: [],
  },
  {
    ownerName: "Rahul Joshi",
    dob: new Date("1997-01-20"),
    contact: "9890123457",
    category: ["Rooms"],
    placeType: "Private room",
    manualAddress: "Viman Nagar, Pune",
    geometry: { type: "Point", coordinates: [73.9189, 18.5678] },
    location: "Pune, Maharashtra, India",
    guests: 1,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    image: { url: "https://images.unsplash.com/photo-1499916078039-922301b0eb9b?auto=format&fit=crop", filename: "listing_16" },
    title: "Clean & Quiet Room for Students/Pros",
    description: "A simple, clean private room with a study desk, ideal for students or working professionals.",
    price: 1500,
    residentialAddress: "C-304, Rohan Mithila, Viman Nagar, Pune, Maharashtra 411014, India",
    reviews: [],
  },
  {
    ownerName: "Fatima Begum",
    dob: new Date("1984-08-08"),
    contact: "8790123456",
    category: ["Iconic cities"],
    placeType: "Entire place",
    manualAddress: "Charminar, Hyderabad",
    geometry: { type: "Point", coordinates: [78.4747, 17.3616] },
    location: "Hyderabad, Telangana, India",
    guests: 6,
    bedrooms: 3,
    beds: 4,
    bathrooms: 2,
    image: { url: "https://images.unsplash.com/photo-1549924231-f129b911e442?auto=format&fit=crop", filename: "listing_17" },
    title: "Traditional Home in Old City",
    description: "Experience the culture of Hyderabad in this traditional home located near the historic Charminar.",
    price: 6500,
    residentialAddress: "H.No. 2-4-56, Moghulpura, Hyderabad, Telangana 500002, India",
    reviews: [],
  },
  {
    ownerName: "Sandeep Menon",
    dob: new Date("1987-07-07"),
    contact: "7690123456",
    category: ["Beaches", "Countryside"],
    placeType: "Entire place",
    manualAddress: "Marari Beach, Kerala",
    geometry: { type: "Point", coordinates: [76.3114, 9.601] },
    location: "Mararikulam, Kerala, India",
    guests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    image: { url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop", filename: "listing_18" },
    title: "Secluded Beach Cottage",
    description: "A private fisherman's cottage converted into a beautiful stay on the quiet Marari Beach.",
    price: 7000,
    residentialAddress: "Marari Dreamz, S.L. Puram, Mararikulam North P.O., Alappuzha, Kerala 688523, India",
    reviews: [],
  },
  {
    ownerName: "Tenzin Dorje",
    dob: new Date("1999-09-09"),
    contact: "6590123456",
    category: ["Mountains"],
    placeType: "Shared room",
    manualAddress: "Dharamshala, Himachal Pradesh",
    geometry: { type: "Point", coordinates: [76.3232, 32.219] },
    location: "Dharamshala, Himachal Pradesh, India",
    guests: 1,
    bedrooms: 1,
    beds: 1,
    bathrooms: 2,
    image: { url: "https://images.unsplash.com/photo-1599557223495-2432f505342a?auto=format&fit=crop", filename: "listing_19" },
    title: "Backpacker's Bunk in McLeod Ganj",
    description: "A comfortable bunk bed in a vibrant hostel, a great place to meet fellow travelers.",
    price: 750,
    residentialAddress: "The Wanderer's Nest, Jogiwara Road, McLeod Ganj, Dharamshala, Himachal Pradesh 176219, India",
    reviews: [],
  },
  {
    ownerName: "Aishwarya Rao",
    dob: new Date("1991-05-21"),
    contact: "9901234567",
    category: ["Iconic cities"],
    placeType: "Entire place",
    manualAddress: "T. Nagar, Chennai",
    geometry: { type: "Point", coordinates: [80.2312, 13.042] },
    location: "Chennai, Tamil Nadu, India",
    guests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    image: { url: "https://images.unsplash.com/photo-1562778663-1d013a483b8b?auto=format&fit=crop", filename: "listing_20" },
    title: "Centrally Located Service Apartment",
    description: "A fully furnished service apartment in the shopping district of T. Nagar.",
    price: 3200,
    residentialAddress: "No. 5, Ranganathan Street, T. Nagar, Chennai, Tamil Nadu 600017, India",
    reviews: [],
  },
];

// To use this in your seed file:
// const Listing = require("./models/listing.js");
// Listing.insertMany(sampleListings)
//   .then(res => console.log(res))
//   .catch(err => console.log(err));

module.exports = { data: sampleListings };